### ISSUE TITLE
Linbox is linking to openblas, but openblas not in requirements

### ISSUE THREAD

**Issue by isuruf** [conda-forge/linbox-feedstock#3]
Latest linbox conda package is compiled against openblas 0.2.19, but other packages like sagelib are compiled against 0.2.20.
See travis log in https://github.com/conda-forge/sagelib-feedstock/pull/18

cc @saraedum

**Comment by saraedum** [comment]
I think the relevant travis log is in https://github.com/conda-forge/sage-feedstock/pull/11.

**Comment by saraedum** [comment]
Fixed in #4.
